### ISSUE TITLE
Full screen wall option offset issue

### ISSUE THREAD

**Issue by sinedied** [braz96/skin.mimic#13]
Hello,

I have latest stable Kodi version installed with mimic updated to this version and have a small issue with the full screen wall display: there is a gap in the bottom of the screen where I can see the background, and an equivalent part of the top row is cut at the top: in a word, the whole wall is offset by a bit in the top, which is annoying.

I use OSMC on a Raspberry Pi 2, for additional info.

**Comment by bryanbrazil** [comment]
Can't duplicate the issue here, can you post a screenshot?

**Comment by sinedied** [comment]
I will post screens when I get back home in 4 days. As additional info, I forced the output resolution to 720p, maybe its related.

**Comment by bryanbrazil** [comment]
Yeah, sounds like a rounding issue with forcing 720p resolution, not a skin issue.

**Comment by sinedied** [comment]
What's strange is that I did not had issue with other skins which also had a full screen wall :/

**Comment by sinedied** [comment]
I just tried with 1080p resolution and it is exactly the same.

I attached 2 photos (no keyboard on my RPi2), notice the gap on the bottom and the cut selection at the top:
![img_20150613_195837](https://cloud.githubusercontent.com/assets/593151/8145418/ec06e770-1207-11e5-9a8b-b0bf95ae8993.jpg)
![img_20150613_195919](https://cloud.githubusercontent.com/assets/593151/8145424/20339340-1208-11e5-8ca0-fa6b4067728a.jpg)

**Comment by bryanbrazil** [comment]
Are you sure it's only that view that is off, and not the entire skin? It
looks like an issue with overscan or screen position on your TV. Recommend
playing with the screen alignment settings in Kodi, it's not likely a skin
issue.

**Comment by sinedied** [comment]
Yes, I'm sure since I did a fresh reinstall, and it does it only with this view mode. Every other view mode or the rest of the UI does not have this issue. For example, the other view closest to this view "wall + info" does not have the offset.

I tried playing with screen position in kodi, reset it, no luck. The issue is visible on every screen I tried (PC monitor, TV, videoprojector).

**Comment by bryanbrazil** [comment]
Just took a look at the code and see I have the top of that view positioned -15. I'm guessing that's what is causing the issue. Not sure what's different about our systems that causing it...I haven't heard from any other users about positioning issues. That code is needed for Wall and several other views to be positioned properly on my system. Will test further.
