### ISSUE TITLE
Widget background issue

### ISSUE THREAD

**Issue by HotMykeul** [braz96/skin.mimic#21]
Hello,
Thanks for your beautiful theme, I like it. But I have an issue:

The widget background doesn't appear (tablet mode widget stay), it appear after 5 minutes, and stay in all categories without widgets.
I'm on openelec 6 runing on rpi 2

![img_20151105_123438](https://cloud.githubusercontent.com/assets/1063311/10967376/77134e7a-83ba-11e5-874f-766c05aa9820.jpg)
 
Sorry for my bad english

**Comment by bricewge** [comment]
I have the same issue here with OSMC on a RPi2, it happened when the theme's setting`Always show widgets` is on.

**Comment by bryanbrazil** [comment]
I haven't been able to reproduce this, is it still an issue? Could be a hardware issue, I only have Windows 10 HPTCs to test.

**Comment by svichit21** [comment]
Amazing skin, but I'm having similar issue, widgets won't load on startup. It not staying. Any way to fix?

**Comment by braz96** [comment]
@svichit21 

Is your issue similar (backgrounds), or are the widgets not loading? Sounds like you're talking about a different issue. You'll need to explain exactly what it is doing and post a link to your debug log.
