### ISSUE TITLE
PVR Menus

### ISSUE THREAD

**Issue by badnazo** [braz96/skin.mimic#30]
Hi,
First, Thanks for your cool theme, which support RomCollectionBrowser 1080p.
I'm actually trying to setup PVR (SimpleIPTV) on Kodi 16.1rc running on Debian x64, and seems like the 'LiveTV' doesn't appear when mimic is enabled, but when i revert to AeonNox & Confluence, it show the menu (still have to figure out the correct formating for the m3u file)
Also, during tests, i've updated to git master, and seems like you can't come back from the right sidebar in the option menu (using x360 controller and keyboard)
Sorry for the incorrect english here

**Comment by bryanbrazil** [comment]
Mimic uses script.skinshortcuts for its main menu while AeonNox and Confluence do not. You'll need to add it in the menu customizer. Skin settings > Home window > Setup menus and widgets.

Not sure what you mean about coming back from the right sidebar. You might have to show me a screenshot.

**Comment by badnazo** [comment]
My mistake, LiveTV works fine. Menu doesn't appear if m3u file loaded by simpleIPTV PVR is misformated, which seem normal :)

But here is a screenshot of the settings home screen (http://uploadpie.com/2Soik), and if i go on the far right, seems like i can't go back from the scrollbar (couldn't take a correct screenshot with scrollbar highlighted). I found this when i was trying to see if you hided a option to revert to 3.3.1 menu, which looked cool on 16:9 TV (but probably less on mobile/touch i suppose)

**Comment by bryanbrazil** [comment]
That screenshot doesn't load. Not sure which scrollbar you are referring to, I can't find any that don't work.

**Comment by badnazo** [comment]
Oh, Crapy screenshot, sorry.
I was reffering to the kodi settings menu (the new one, with bigger icons). Pulled last git version fixed it, so i guess just WIP.

**Comment by braz96** [comment]
Glad it's working!
