### ISSUE TITLE
Main Settings Menu now Thumbnail view

### ISSUE THREAD

**Issue by bonzenpaule** [braz96/skin.mimic#32]
Hello, the last update (3.4.0) added some usefull features and I am greatfull for that. But in the process you changed the main settings menu view from a 2 collums view to thumbnail view. Please give us the option to change that back. I can't find any way to change it back myself (searched through Skin settings, settings.xml & Kiosk mode is disabled).
Thanks for an otherwise really beautifull skin.

**Comment by braz96** [comment]
Will think about it, but currently no plans to add an option for the old view.

**Comment by twnsnd** [comment]
Hi, if there are no plans to change to the old view would it be possible for a quick tip on which file to look in to change it ourselves?

**Comment by braz96** [comment]
You might be able to just replace Settings.xml with the one from the previous Mimic version.

**Comment by jpcarey** [comment]
Everything fit on the old menu, now you must "scroll" (without an indication that other items are off screen). I am failing to see how this is an improvement.

**Comment by braz96** [comment]
I am failing to see why having to scroll is a problem. How often do you access profiles and information anyway? I guess I could remove 2 item. Skin Settings isn't really needed since its official home is under Appearance. And Addons is just a link to the addon browser, it's not a settings category.

**Comment by jpcarey** [comment]
I personally don't mind the icons (although, I did prefer the previous look to the new), and agree that scrolling isn't often. My point is to the fact that there are items off screen without any real indication. Reducing the number of top level items is a good solution.

**Comment by braz96** [comment]
After reviewing all of the settings items again, and checking Confluence, I decided to remove Addons and System Information from the settings window so everything fits. Addons and System Info can be added as submenu items if needed.
