### ISSUE TITLE
Recently Added Episodes/Movies not updating when watched

### ISSUE THREAD

**Issue by ragincajunintx** [braz96/skin.mimic#34]
I've tried resetting Kodi to scratch. I'm using 16.0 on Nexus Player, AFTV2, and AFTV.

**Comment by braz96** [comment]
Are you referring to the widget not updating, or the library view? If you are referring to your widget, see the following thread:

http://forum.kodi.tv/showthread.php?tid=264907

**Comment by ragincajunintx** [comment]
Thank ks for the thread, but I don't have a shutdown menu. I just have the option for a shutdown shortcut. I'll try connecting a keyboard.

**Comment by ragincajunintx** [comment]
OK, so I mapped a submenu shortcut to XBMC.ReloadSkin() and I tried changing the widget to recentepisodes instead of Recently Added Episodes, no dice. The widget doesn't update even after restarting Kodi.

**Comment by braz96** [comment]
Don't know what to tell ya, it's not really a skin issue as the widget and menu functionality is provided by other scripts.

I haven't tested it, but the script.skinshortcuts author posted an updated version of the script that will reload the widgets...

http://forum.kodi.tv/showthread.php?tid=217174&pid=2292207#pid2292207

**Comment by ragincajunintx** [comment]
OK! I finally got the script.skinshortcuts updated from the PR'd branch and followed the instructions to get it going...so If I understand this right...you don't provide the widgets, you just link out to the script to grab the widgets, correct? The only reason that I ask, is the eventual fix will be to fix the widgets, then I will volunteer my time and testing on the Ignobles61 page, however, if there is a change that you need to make, I'd be happy to volunteer my time and efforts to help you make it happen...Mimic has by far been my favorite for over a year after getting frustrated with the 90s feel of the Amber skin! So thank you for your help and time, and please let me know if there is anything that I can do to help!

**Comment by braz96** [comment]
I will implement a fix when it is available. You can keep tabs on the bug ticket for this issue here:

http://trac.kodi.tv/ticket/16635
