### ISSUE TITLE
High CPU on RPI

### ISSUE THREAD

**Issue by yamlfd** [braz96/skin.mimic#36]
I tried installing mimic on my rpi 2, but it looks hanging very often. After some digging I have seen that the cpu is nearly always at 100%. Any chance mimic may work more fluent on RPI?

It is really the best skin for kodi and my default... Do not like to use any other.

OpenElec 6.0.3

**Comment by braz96** [comment]
I would think the rpi 2 is powerful enough, as others have run it on the original rpi. I don't have either though, and have never tested the skin on low-powered hardware. Probably not much I can do that wouldn't involve completely redesigning the skin.

**Comment by yamlfd** [comment]
I'm not sure what is causing the high cpu. We should find out very first.

Maybe you have an idea so I can try a few things like disabling animations or so. 

I do not say it does not work... Its just very slow because of 100% cpu load and every click takes a lot more time than normally on faster systems. The loading circle is shown everywhere. The high load makes it very unresponsive...

Maybe we can find the root cause and turn off what is causing this and we are done... Without big changes to mimic.

**Comment by braz96** [comment]
If there is a certain area that is sluggish it might be able to pinpoint the cause. If it's the entire skin, though, I wouldn't know where to start.

**Comment by braz96** [comment]
My guess, based on other discussions I've seen on the forum, is that the busy animations themselves may be a problem on the rpi. You can test by removing the busy animations from 2 places.

1) 1080i/Includes.xml, search for "busy animation" and comment out that control.

2) shortcuts/template.xml, search for "WidgetBusyAnimation" and comment out each one of those includes you find.
