### ISSUE TITLE
Power menu is missing in Kodi 16 / cannot reboot

### ISSUE THREAD

**Issue by yamlfd** [braz96/skin.mimic#37]
Not sure why, but under kodi 16 the power menu is missing. That makes it very difficult to restart, shutdown, standby the openelec system.

Tested with
- Kodi 16.0 on Windows 10
- OpenElec 7.0 Beta1

**Comment by braz96** [comment]
This skin uses script.skinshortcuts, so the menu is fully customizable. Recommend adding whichever power options you'd like to the menu.

**Comment by yamlfd** [comment]
In openelec 6 the power menu exists. Why have you removed it now? It is important and should exists by default. Confluence theme also has a power button in kodi 16.

Please add it back by default.

**Comment by braz96** [comment]
The skin now fully uses script.skinshortcuts for all menus. I haven't specified any main menus, the defaults are provided by the script. No plans to add defaults as everyone can customize the menu as they see fit. It will take you less than a minute to add it to your menu.
