### ISSUE TITLE
OpenElec program has unsharp fonts

### ISSUE THREAD

**Issue by yamlfd** [braz96/skin.mimic#38]
If you mde mimic your default skin and than start the openelec program the fonts are totally unsharp und you cannot read it. I'm not sure if this is a mimic or openelec issue.

Openelec 6.0.3

**Comment by braz96** [comment]
You'll need to post a screenshot, you're the first to report this.

**Comment by yamlfd** [comment]
I need to correct me. This requires OpenElec 7.0 Beta 1 - in 6.0 it looks good. I have rolled back to 6.x as 7.x had some too many issues. So I cannot provide a screenshot currently. Maybe someone else can. Please note that this is only visible after Mimic skin has been activated and you go to Programs > "OpenELEC Configuration".

**Comment by braz96** [comment]
Sounds like an issue with the skin for the OpenElec config window, not Mimic related.
