### ISSUE TITLE
the dependency on xbmc.gui version 5.11.0 could not be satisfied

### ISSUE THREAD

**Issue by Bang257** [braz96/skin.mimic#39]
Hello,

Sorry to return with another issue
While trying to install Mimic from zip, I'm getting "the dependency on xbmc.gui version 5.11.0 could not be satisfied"

Do I need to drop down to a previous version of Kodi to use Mimic for now? (Mimic is my favorite addon, so it would certainly be worth it)

Thank you!

**Comment by braz96** [comment]
The master branch on github is now for Kodi 17 Krypton only. I'm guessing you have tried to install it on Kodi 16 Jarvis. So you have 2 choices...you can upgrade to the latest Kodi 17 nightly, or install Mimic 3.4.1 from the Jarvis branch on github.

https://github.com/braz96/skin.mimic/archive/jarvis.zip

**Comment by Bang257** [comment]
Thank you for the help! (Especially so quickly)

I apologize for the dumb question -- I must have missed the transition to the Kodi 17 build becoming the master on Github. Makes complete sense in hindsight

Thanks for taking the time to reply,
Have a good weekend
