### ISSUE TITLE
high cpu usage / 60 fps when showing background images on media view 

### ISSUE THREAD

**Issue by noXtreme21** [braz96/skin.mimic#42]
Hi,

Normally the Kodi interface (menu) will rendered with ~5 frames per second when nothing is animated (no rss feeds, no animated descriptions). Actually this works. But if you're using the mimic theme and navigate to a media library (tv-shows/movies) then the screen is every time rendered with full 60 fps which affects a higher CPU usage. This happens also if the system is/should idle.

I figured out, if no background images are shown (I don't know how I had disabled them temporary from the library view) then I got the expected ~5 frames per seconds and a lower CPU usage.

I tried to setting up the dirty regions settings but it doesn't changed the behavior. Is this high fps on the media library really necessary in fact of that nothing is really animated on the view? Or is this eventually a bug? I tried some other kodi skins which haven't this issue.

**Comment by braz96** [comment]
What Mimic version are you using? This skin uses the same method to display library fanart as any other skin, no idea why there would be a difference. I recently changed the home background to use skin.helper.service provided fanart, this might slow things a bit for low powered devices on startup. This is only available in the Kodi18 branch on github though.

**Comment by noXtreme21** [comment]
I am using Kodi v16.1 Jarvis with Mimic version 3.4.1 on a Mac Mini. Everything with the fps on the home screen is fine. The issue is just on the library view. Actually the issue itself feels not like a bug. The system runs very well. I just wondering why the fps is so high which produce a higher cpu temperature on idle. I also can't see any abnormalities in the debug log. 

So I will try the version from the Kodi18 branch.

**Comment by braz96** [comment]
If the system is running fine, I wouldn't install another version. And the master and kodi18 branches on github are for Kodi 17 only. 

Don't worry about the cpu numbers unless they stay at 100% and you are experiencing lag.
