### ISSUE TITLE
Unable to add shortcuts

### ISSUE THREAD

**Issue by ProjectAdrian** [braz96/skin.mimic#44]
Ver 4.0.3 for Kodi 17 is unable to add shortcuts on main menu and submenu under skin settings..
is there another way round?

**Comment by braz96** [comment]
If you're running one of the latest nightlies, make sure you have the latest script.skinshortcuts from github and the latest Mimic 4.x from github. Some of the window names were removed from Kodi, the fixes are on github.

**Comment by ProjectAdrian** [comment]
So what is the version for scriptshortcuts that is required.. im running on kodi 17 alpha2.. mimic ver 4.0.3

Date: Sat, 2 Jul 2016 21:21:38 -0700

**Comment by ProjectAdrian** [comment]
ive updated my script skin shortscut but im still not able to add new mainmenu or submenu on skin settings under setup menu and widgets.

**Comment by IneptGarbage** [comment]
I'm using the new Kodi 17 alpha v2 with Mimic 5.0.0 and I'm having the same issue. I just want to have the option to delete menu items and add my own like I could on Kodi 16 with the older Mimic skin. I understand it's very new, so I hope there are some workarounds for this. I've also updated my skin shortcuts & reopened Kodi, but that didn't work.

**Comment by IneptGarbage** [comment]
What I mean specifically is that there are no "add" or "delete" options for each menu item. http://i.imgur.com/nAYda0W.png

**Comment by braz96** [comment]
Ah, those buttons have been moved to the context menu. Focus on a menu item
and press "c".

**Comment by IneptGarbage** [comment]
Thank you so much! I feel kinda stupid now. This helps a lot. I really appreciate your work & your skin is by far my favorite.

**Comment by ProjectAdrian** [comment]
i've tried but the context menu wont show up

**Comment by braz96** [comment]
@ProjectAdrian

I don't know what to tell you, make sure you've manually installed the latest of everything from github. Or wait until the skin and required scripts push updates to the Kodi repo.

**Comment by delian7** [comment]
@braz96 I have Kodi on an Apple TV setup. I don't have a 'c' button. Usually I can access a context menu if a just press and hold enter key (keyboard) or big button on remote but no context menu shows up when I focus on a menu item.

**Comment by braz96** [comment]
No idea about Apple TV.
