### ISSUE TITLE
Missing menu items after install

### ISSUE THREAD

**Issue by lynnbess** [braz96/skin.mimic#45]
After install only 5 items show on menu bar are PICTURES VIDEO MUSIC PROGRAMS SETTINGS

when I go to setting  can see others like WEATHER  but not POWER 

I installed on a fresh install of KODI JARVIS 16.1

**Comment by lynnbess** [comment]
forgot to add that I'm doing this on a Win 10 desktop

**Comment by braz96** [comment]
Can you press left/right to reach the other menu items? If this is a fresh install, and you haven't set up another skin that uses script.skinshortcuts, then it should display the script's default menu items. Haven't used Jarvis in quite a while, so not sure if you might need to update script.skinshortcuts, etc.

**Comment by lynnbess** [comment]
I uninstalled and then reinstalled Jarvis and got the same results.

I then uninstalled Jarvis and installed Krypton and even less icons showed up. I'm beginning to think it maybe my machine. I will try to repeat this on a Win 8 machine and see what happens. I'll also try it on my android box and let you know the results by Thursday.
