### ISSUE TITLE
100% background color opacity is not fully opaque

### ISSUE THREAD

**Issue by kq01526** [braz96/skin.mimic#47]
@braz96 :

When setting a custom color via the color customizer, it's possible to set the opacity of the background color.

But even if it is set to 100%, it's still a bit transparent.

Any chance you could fix that?

Regards

**Comment by braz96** [comment]
That's because the underlying texture is slightly transparent. No plans to change that. You could create a new theme and make all of the textures opaque, that would probably be the simplest approach.

**Comment by kq01526** [comment]
> @braz96 wrote:
> make all of the textures opaque

Can you please point to the specific files in the repo?

**Comment by braz96** [comment]
You would need to make opaque versions of the relevant textures in the following folder, create a new theme, and then build it using TexturePacker.
