### ISSUE TITLE
Add option to use bold version of each font

### ISSUE THREAD

**Issue by kq01526** [braz96/skin.mimic#49]
@braz96 :

Any chance you could add an option to use the bold version of each font?

Most fonts are rather thin. Setting them to bold might improve the readability.

This should be an option though. So, users which would prefer to use the regular version of the font, should still be able to use the regular version, whereas users which prefer the bold version should be able to enable the bold version via an option.

Regards

**Comment by braz96** [comment]
Sorry, no plans to add bold versions. I feel like while the default font is rather thin, there are already plenty of other options that are heavier.

**Comment by kq01526** [comment]
Thanks for the swift reply.

> @braz96 wrote:
>  there are already plenty of other options that are heavier.

Well, not really. I've also checked the new fonts in Mimic 5.x. There's only Arial which is somewhat heavier. Jaldi and NotoSerif are also somewhat heavier. But Arial is not necessarily the most beautiful font..., same goes for the other ones...

All the other fonts are rather thin.

**Comment by braz96** [comment]
You'll have to manually add a bolder font then. Or replace one of the ones in the fonts folder with its bolder variant.
