### ISSUE TITLE
Increasing font size?

### ISSUE THREAD

**Issue by kq01526** [braz96/skin.mimic#50]
@braz96 :

KODI users are currently complaining all over the place on the KODI forum because the new Estuary skin has such bad readability and such small fonts and wastes so much screen space:

http://forum.kodi.tv/showthread.php?tid=263958

Mimic is already way better than Estuary in that regard.

However, would there be any chance you could still increase the font size in Mimic or add an option to increase the font size?

Setting ***View = List + Slim list = Off + Wide list = On*** already helps a lot for readability (thanks a lot, this is awesome :slightly_smiling_face:).

But it actually wouldn't hurt if the fonts in Mimic would be even bigger.

As you can see from the forum thread mentioned above, font size and readability is really important for users.

So, if you could manage to increase the font size in Mimic even further, that would be really nice.

Regards

**Comment by braz96** [comment]
Sorry, won't be changing the font size. It's not really possible to allow options for font size with Kodi's skinning engine. You'd end up with a lot of cut off lines of text.
