### ISSUE TITLE
Mouse control on default home layout

### ISSUE THREAD

**Issue by Dimpl** [braz96/skin.mimic#54]
Mouse control is incompatible with the default home layout: mousing over an option brings up a submenu for the currently selected option (via keyboard), rather than the option that was hovered over.

**Comment by braz96** [comment]
Why are you using a mouse and keyboard at the same time? Don't consider this an issue, you should use a single input device.

**Comment by Dimpl** [comment]
I included the 'via keyboard' for clarification, the issue exists for mouse control. An easy workaround is to enable 'always show submenus'.

**Comment by braz96** [comment]
You must be using an earlier version then, this has likely been fixed in Mimic 5. Please let me know if you find otherwise.

**Comment by Dimpl** [comment]
I am using version 3.4.2, which is the newest available version in the client. Where is Mimic 5 available?

**Comment by braz96** [comment]
Mimic 5 is in the Kodi 17 repo and downloadable directly from here on Github.
