### ISSUE TITLE
Library Fan Art

### ISSUE THREAD

**Issue by keesee** [braz96/skin.mimic#56]
I recent discovered both Kodi and Mimic.  You've done an amazing job moderizing the UI.  Congrats, and thanks for the work you've put in. :)

I was playing around with the Library and noticed that the background doesn't change the fanart as I scroll through the episodes.  It just uses the show fanart not that of the episode.  (I currently use low list).    In Quasar and other apps i get extra fan art backgrounds for each episode, but not if I view them from my library after I've added them.   Have I missed a setting?  I also don't have art work config option in my left panel for tv episodes in the library.  I looked through the XML but need to spend a bit more time aquinting myself with how Kodi is put together.   

Thanks in advance for any tips :)

**Comment by braz96** [comment]
That's the way it is designed. I'm not aware of any Kodi skins that display episode-specific fanart.
