### ISSUE TITLE
Poster Widget view: Remove black background and bezel

### ISSUE THREAD

**Issue by aareya** [braz96/skin.mimic#58]
When setting up widgets for the main menu is there a way to remove the "per-item" background and "bezel" for the poster view? Currently, Poster view shows the poster in front of a black square surrounded by the almost transparent bezel. So basically there is no difference between the Poster view and the Thumbnail view.

**Comment by aareya** [comment]
So looking at this issue again, I notice the the "per-item" black sqaure background and the transparent bezel is active on all widget items. Any way to easily turn off? I'm looking through the code to see if a recognize anything off hand to change. I'm new to skinning but not new to Kodi or programming. Any reason this was changed from earlier versions?

**Comment by braz96** [comment]
It was too hard to position the various icon types in a sane way, so went with thumbnail view for all widgets. Look in Includes_Widgets.xml if you want to change it.
