### ISSUE TITLE
Update to 5.0 fails on Krypton beta 6

### ISSUE THREAD

**Issue by mz83** [braz96/skin.mimic#59]
Trying to update from the most recent 4.x version to 5.0 leads to a successful download, followed by an "Update failed" message at 4% progress.
A look inside Kodi's log file doesn't reveal anything beyond the following lines either:

23:25:29.461 T:3516   ERROR: XFILE::CFile::Rename - Error renaming file C:\Users\HP\AppData\Roaming\Kodi\temp\3eff98dd-6420-42f5-b48e-c13976c7378e
23:25:29.461 T:3516   ERROR: Failed to move new addon files from 'C:\Users\HP\AppData\Roaming\Kodi\temp\3eff98dd-6420-42f5-b48e-c13976c7378e' to 'C:\Users\HP\AppData\Roaming\Kodi\addons\skin.mimic'

**Comment by mz83** [comment]
Current workaround is to save a backup of the settings, uninstall the skin in Kodi, close Kodi, manually delete the Mimic folders in the user profile and then to start Kodi again and install a ZIP file of 5.0 that's been downloaded from GitHub. Then import the settings backup and adjust as needed.

**Comment by braz96** [comment]
Mimic 5 is now available from the Kodi repo, no need to manually install anymore. That error sounds like a filesystem issue.

**Comment by mz83** [comment]
The error occurs if you're using the repo to update to the newest version. Seems to be a bug where Kodi tries to handle the directory as if it's a file (XFILE::CFile::Rename), which obviously won't work. Works fine with most addons, but apparently in the case of mimic, only circumventing the update procedure by performing a fresh install from a ZIP file seems to work in the current beta.
