### ISSUE TITLE
Background Fanart Scaling (override kodi default)

### ISSUE THREAD

**Issue by jstnthrstpdsr** [braz96/skin.mimic#66]
With the current GitHub version background fanart seems to use the kodi default scaling behaviour **stretch** - which looks odd if fanart doesn't come in standard size which is often the case with my collection. It seems (I'm not really familiar with Kody skinning apart from happily using the great Mimic skin) that adding 

```
<include name="FullscreenDimensions">
...
	<aspectratio>scale</aspectratio>
</include>
```
to _/1080i/Includes_CommonValues.xml_ does make things look better IMHO.
If possibly it would be nice to have this value set by default / added to the include; wouldn't it look better than stretch?

BTW I've noticed Omni uses the same standard scaling value.

**Comment by braz96** [comment]
That's the wrong place to put it, it should go with the image and multiimage controls. Where are you seeing stretched backgrounds? As far as I can tell, all of them are already set to scale.

**Comment by jstnthrstpdsr** [comment]
I thougth it'd be wrong - but it worked. ;) 
The problem occurs with the Video Information backgrounds (and when using "view fanart" from there). Maybe there's nothing defined for fanart behind video information yet.

**Comment by braz96** [comment]
Thanks, just needed to know exactly where it's happening. Just pushed a fix to Github. Let me know if you notice any more stretched backgrounds.

**Comment by jstnthrstpdsr** [comment]
Thanks to you! Problem's gone - no more stretching... Great. :)

**Comment by braz96** [comment]
Thanks for reporting!
