### ISSUE TITLE
Trakt.tv Progress Widget doesn't show title

### ISSUE THREAD

**Issue by ragincajunintx** [braz96/skin.mimic#68]
Hey braz,
In 16.1 Mimic I had a widget on my homescreen for trakt.tv progress and it actually showed the poster of the show with the title of the show on it. No description or episode name or anything... in 17.1 If i select Poster for the art style, it shows the poster with the show name, but also a GIANT box with the description on it. Would it be possible to add an option to turn the description off?

**Comment by braz96** [comment]
Won't be adding any more options, sorry. Your best bet is to choose thumbnail for the widget icons, then the plot won't be shown.

**Comment by ragincajunintx** [comment]
When I select thumbnail, it shows the fan art or episode thumbnail instead of the "poster" like it did on 16.1. If this is on purpose, then I'll close the ticket, because I respect you and love the work you do...
