### ISSUE TITLE
Add-on view returns to default

### ISSUE THREAD

**Issue by Thomas-O** [braz96/skin.mimic#73]
I am really enjoying your shameless amalgamation. Especially the streamlined new version.
The only small problem I've had, and the reason for this issue notice, is that I am unable to retain a preferred view within a single add-on. I select Big List, but then on re-opening the add-on find that it has returned to the default List view.

The add-on is a TV catch up viewer and reloads the content each time. This might have something to do with its refusal to retain the chosen option. Is there anything I can do to keep things in place? Perhaps by making Big List the default view for all screens.

**Comment by braz96** [comment]
I saw from your post on the forum that you are using banned addons, and I can't support those. I will say though, that Kodi remembers the views, not skins. You will find this to be the case with all add-ons.

**Comment by Thomas-O** [comment]
Thank you. I understand. I will try to remedy it myself or just live with what is really only a tiny anomaly and slight annoyance.
 
BTW, at the time of the forum post I wasn't aware that the repo and add-on was banned. Though, of course, that's no defence for this subsequent report.  If I was trying to defend myself I'd add that it's the only add-on I have which does anything even slightly prohibited. Even then it's just providing a stream (from an open API) which is perfectly legal for UK residents. Which is where this keyboard is located. It really shouldn't be banned. But then I suppose it's because of its origins in a banned repo.
