### ISSUE TITLE
Add IMDB rating and MPAA ratings to additional views

### ISSUE THREAD

**Issue by xbmcnut** [braz96/skin.mimic#75]
Hi there,

I've recently discovered Mimic after using both Titan and Xonfluence for a very long time and I must say, it's the best skin I've seen hands down. Clean, fast and just customizable enough to make it very powerful. Well done. I'd recommend it as a must have skin for anyone using the default under Krypton.

One feature request I have though is the ratings listed above addtional views for the TV Shows and the LowPanel view for movies. We have family movie night on Fridays and we're always looking at two things when trying to choose a movie; the IMDB rating and whether it's suitable for the kids (<PG13). If these were displayed in the LowPanel view for movies along with the media flags, that would be awesome! Would save having to push info on every movie.

The IMDB rating is displayed in the List and LowList views for TV Shows but visibility in some other (where appropriate) views would also be appreciated.

Thanks for your great work.

**Comment by gnjnshh** [comment]
I scoured through many posts on kodi skin and this came as highly recommended. 
However, the above point is very important to **find new content**. Everything else is really perfect, this should be really the default skin when installed. 

Keep up the great works, thanks,

**Comment by braz96** [comment]
Thanks! No plans to change it though, prefer to have all of that info in the info dialog and not in the views.
